apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mla-back
  name: mla-back
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3001
  selector:
    app: mla-back
  type: NodePort
status:
  loadBalancer: {}
